language: node_js

node_js:
  - "8"

branches:
  only:
    - master

cache: yarn

install:
  - yarn

deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
